id: require-tsconfig-typecheck-no-property-access-from-index-signature
valid:
  - |
    {
      "compilerOptions": {
        "noPropertyAccessFromIndexSignature": true
      }
    }
  - |
    {
      "extends": "./tsconfig.json",
      "compilerOptions": {
        "noEmit": true,
        "noPropertyAccessFromIndexSignature": true
      }
    }
invalid:
  # explicitly disabled
  - |
    {
      "compilerOptions": {
        "noPropertyAccessFromIndexSignature": false
      }
    }
  # missing entirely
  - |
    {
      "compilerOptions": {
        "noEmit": true
      }
    }
  # no compilerOptions at all
  - |
    {
      "extends": "./tsconfig.json"
    }
