id: require-tsconfig-typecheck-no-unchecked-side-effect-imports
snapshots:
  ? |
    {
      "compilerOptions": {
        "noEmit": true
      }
    }
  : labels:
    - source: |-
        {
          "compilerOptions": {
            "noEmit": true
          }
        }
      style: primary
      start: 0
      end: 49
    - source: |
        {
          "compilerOptions": {
            "noEmit": true
          }
        }
      style: secondary
      start: 0
      end: 50
  ? |
    {
      "compilerOptions": {
        "noUncheckedSideEffectImports": false
      }
    }
  : labels:
    - source: |-
        {
          "compilerOptions": {
            "noUncheckedSideEffectImports": false
          }
        }
      style: primary
      start: 0
      end: 72
    - source: |
        {
          "compilerOptions": {
            "noUncheckedSideEffectImports": false
          }
        }
      style: secondary
      start: 0
      end: 73
  ? |
    {
      "extends": "./tsconfig.json"
    }
  : labels:
    - source: |-
        {
          "extends": "./tsconfig.json"
        }
      style: primary
      start: 0
      end: 34
    - source: |
        {
          "extends": "./tsconfig.json"
        }
      style: secondary
      start: 0
      end: 35
