id: require-composed-check
snapshots:
  ? |
    {
      "scripts": {
        "build": "tsc"
      }
    }
  : labels:
    - source: |-
        {
          "scripts": {
            "build": "tsc"
          }
        }
      style: primary
      start: 0
      end: 41
    - source: |
        {
          "scripts": {
            "build": "tsc"
          }
        }
      style: secondary
      start: 0
      end: 42
  ? |
    {
      "scripts": {
        "check": "lefthook run pre-commit"
      }
    }
  : labels:
    - source: |-
        {
          "scripts": {
            "check": "lefthook run pre-commit"
          }
        }
      style: primary
      start: 0
      end: 61
    - source: |
        {
          "scripts": {
            "check": "lefthook run pre-commit"
          }
        }
      style: secondary
      start: 0
      end: 62
  ? |
    {
      "scripts": {
        "check": "npm run format:check && npm run typecheck && npm run lint && npm run test"
      }
    }
  : labels:
    - source: |-
        {
          "scripts": {
            "check": "npm run format:check && npm run typecheck && npm run lint && npm run test"
          }
        }
      style: primary
      start: 0
      end: 111
    - source: |
        {
          "scripts": {
            "check": "npm run format:check && npm run typecheck && npm run lint && npm run test"
          }
        }
      style: secondary
      start: 0
      end: 112
