id: require-composed-check
snapshots:
  ? |
    {
      "dependencies": {
        "@forge/api": "^4.0.0"
      }
    }
  : labels:
      - source: "@forge/api"
        style: primary
        start: 27
        end: 37
      - source: |-
          "dependencies": {
              "@forge/api": "^4.0.0"
            }
        style: secondary
        start: 4
        end: 52
  ? |
    {
      "dependencies": {
        "@forge/api": "^4.0.0"
      },
      "scripts": {
        "check": "npm run format:check && npm run lint && npm run test"
      }
    }
  : labels:
      - source: "@forge/api"
        style: primary
        start: 27
        end: 37
      - source: |-
          "dependencies": {
              "@forge/api": "^4.0.0"
            }
        style: secondary
        start: 4
        end: 52
  ? |
    {
      "dependencies": {
        "@forge/api": "^4.0.0"
      },
      "scripts": {
        "check": "npm run test && npm run lint && npm run format:check && npm run typecheck"
      }
    }
  : labels:
      - source: "@forge/api"
        style: primary
        start: 27
        end: 37
      - source: |-
          "dependencies": {
              "@forge/api": "^4.0.0"
            }
        style: secondary
        start: 4
        end: 52
