id: tsconfig-for-forge-bundler
snapshots:
  ? |
    {
      "compilerOptions": {
        "module": "CommonJS",
        "target": "ES2022"
      }
    }
  : labels:
    - source: |-
        {
          "compilerOptions": {
            "module": "CommonJS",
            "target": "ES2022"
          }
        }
      style: primary
      start: 0
      end: 79
    - source: |
        {
          "compilerOptions": {
            "module": "CommonJS",
            "target": "ES2022"
          }
        }
      style: secondary
      start: 0
      end: 80
  ? |
    {
      "compilerOptions": {
        "module": "ESNext",
        "moduleResolution": "node",
        "jsx": "react-jsx",
        "target": "ES2022",
        "rootDir": "src",
        "outDir": "dist",
        "strict": true
      }
    }
  : labels:
    - source: |-
        {
          "compilerOptions": {
            "module": "ESNext",
            "moduleResolution": "node",
            "jsx": "react-jsx",
            "target": "ES2022",
            "rootDir": "src",
            "outDir": "dist",
            "strict": true
          }
        }
      style: primary
      start: 0
      end: 197
    - source: |
        {
          "compilerOptions": {
            "module": "ESNext",
            "moduleResolution": "node",
            "jsx": "react-jsx",
            "target": "ES2022",
            "rootDir": "src",
            "outDir": "dist",
            "strict": true
          }
        }
      style: secondary
      start: 0
      end: 198
  ? |
    {
      "include": ["src"]
    }
  : labels:
    - source: |-
        {
          "include": ["src"]
        }
      style: primary
      start: 0
      end: 24
    - source: |
        {
          "include": ["src"]
        }
      style: secondary
      start: 0
      end: 25
